In [74]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats

In [17]:
pre = pd.DataFrame(
    [
        [0.080, 0.076, 0.086],  # CEL
        [0.115, 0.113, 0.124],  # JOD
        [0.050, 0.053, 0.051],  # GAZ
    ],
    index=["CEL", "JOD", "GAZ"],
    columns=["1", "2", "3"],
)
pre

         1      2      3
CEL  0.080  0.076  0.086
JOD  0.115  0.113  0.124
GAZ  0.050  0.053  0.051

In [18]:
post = pd.DataFrame(
    [
        [0.644, 0.667, 0.784],  # CEL
        [0.093, 0.109, 0.105],  # JOD
        [0.433, 0.408, 0.418],  # GAZ
    ],
    index=["CEL", "JOD", "GAZ"],
    columns=["1", "2", "3"],
)
post

         1      2      3
CEL  0.644  0.667  0.784
JOD  0.093  0.109  0.105
GAZ  0.433  0.408  0.418

In [19]:
nasiak = 100*(post - pre)/pre  # %
nasiak

              1           2           3
CEL  705.000000  777.631579  811.627907
JOD  -19.130435   -3.539823  -15.322581
GAZ  766.000000  669.811321  719.607843

In [22]:
mean_std = pd.concat([nasiak.mean(axis=1), nasiak.std(axis=1)], axis=1)
mean_std.columns = ["mean", "std"]
mean_std

           mean        std
CEL  764.753162  54.468044
JOD  -12.664279   8.128144
GAZ  718.473055  48.104379

In [24]:
df = pd.concat([nasiak, mean_std], axis=1)
df

              1           2           3        mean        std
CEL  705.000000  777.631579  811.627907  764.753162  54.468044
JOD  -19.130435   -3.539823  -15.322581  -12.664279   8.128144
GAZ  766.000000  669.811321  719.607843  718.473055  48.104379

In [35]:
print(df.to_latex())

\begin{tabular}{lrrrrr}
\toprule
 & 1 & 2 & 3 & mean & std \\
\midrule
CEL & 705.000000 & 777.631579 & 811.627907 & 764.753162 & 54.468044 \\
JOD & -19.130435 & -3.539823 & -15.322581 & -12.664279 & 8.128144 \\
GAZ & 766.000000 & 669.811321 & 719.607843 & 718.473055 & 48.104379 \\
\bottomrule
\end{tabular}

In [27]:
ph = pd.DataFrame(
    [
        [6.637, 6.669, 6.657],
        [6.787, 6.828, 6.740],
        [6.751, 6.767, 6.744],
    ],
    columns=["1", "2", "3"],
    index=["CEL", "JOD", "GAZ"],
)
ph

         1      2      3
CEL  6.637  6.669  6.657
JOD  6.787  6.828  6.740
GAZ  6.751  6.767  6.744

In [37]:
ref_ph = 6.190
ref_ph

6.19

In [67]:
mean_std = pd.concat([ph.mean(axis=1), ph.std(axis=1)], axis=1)
mean_std.columns = ["mean", "std"]
mean_std = mean_std.round(3)
mean_std

      mean    std
CEL  6.654  0.016
JOD  6.785  0.044
GAZ  6.754  0.012

In [65]:
diff = ph - ref_ph

diff_mean_std = pd.concat([diff.mean(axis=1), diff.std(axis=1)], axis=1)
diff_mean_std.columns=["śr. zmiana", "STD"]
diff_mean_std = diff_mean_std.round(3)
diff_mean_std

     śr. zmiana    STD
CEL       0.464  0.016
JOD       0.595  0.044
GAZ       0.564  0.012

In [78]:
t_stat, p_value = stats.ttest_rel(ph.to_numpy(), np.ones((3, 3)) * ref_ph)
t_stat, p_value

(array([11.8335033 , 12.19273123, 18.46702337]),
 array([0.00706564, 0.00665952, 0.00291945]))

In [77]:
ph_mean_std = pd.concat([ph, mean_std, diff_mean_std], axis=1)
ph_mean_std

         1      2      3   mean    std  śr. zmiana    STD
CEL  6.637  6.669  6.657  6.654  0.016       0.464  0.016
JOD  6.787  6.828  6.740  6.785  0.044       0.595  0.044
GAZ  6.751  6.767  6.744  6.754  0.012       0.564  0.012

In [71]:
print(ph_mean_std.to_latex(float_format="%.3f"))

\begin{tabular}{lrrrrrrr}
\toprule
 & 1 & 2 & 3 & mean & std & śr. zmiana & STD \\
\midrule
CEL & 6.637 & 6.669 & 6.657 & 6.654 & 0.016 & 0.464 & 0.016 \\
JOD & 6.787 & 6.828 & 6.740 & 6.785 & 0.044 & 0.595 & 0.044 \\
GAZ & 6.751 & 6.767 & 6.744 & 6.754 & 0.012 & 0.564 & 0.012 \\
\bottomrule
\end{tabular}