In [85]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [86]:
pre = pd.DataFrame(
    [
        [25, 26, 26],
        [18, 19, 19],
    ],
    columns=["1", "2", "3"],
    index=["AIR", "FREEZE"],
)*0.001
pre

            1      2      3
AIR     0.025  0.026  0.026
FREEZE  0.018  0.019  0.019

In [87]:
print(pre.to_latex(float_format="%.3f"))

\begin{tabular}{lrrr}
\toprule
 & 1 & 2 & 3 \\
\midrule
AIR & 0.025 & 0.026 & 0.026 \\
FREEZE & 0.018 & 0.019 & 0.019 \\
\bottomrule
\end{tabular}

In [88]:
post = pd.DataFrame(
    [
        [1177, 1183, 1208],
        [644, 686, 695],
    ],
    columns=["1", "2", "3"],
    index=["AIR", "FREEZE"],
)*0.001
post

            1      2      3
AIR     1.177  1.183  1.208
FREEZE  0.644  0.686  0.695

In [89]:
print(post.to_latex(float_format="%.3f"))

\begin{tabular}{lrrr}
\toprule
 & 1 & 2 & 3 \\
\midrule
AIR & 1.177 & 1.183 & 1.208 \\
FREEZE & 0.644 & 0.686 & 0.695 \\
\bottomrule
\end{tabular}

In [90]:
nasiak = 100*(post - pre)/pre  # %
nasiak

                  1            2            3
AIR     4608.000000  4450.000000  4546.153846
FREEZE  3477.777778  3510.526316  3557.894737

In [91]:
mean_std = pd.concat([nasiak.mean(axis=1), nasiak.std(axis=1)], axis=1)
mean_std.columns = ["mean", "std"]
mean_std

               mean        std
AIR     4534.717949  79.618370
FREEZE  3515.399610  40.280188

In [92]:
df = pd.concat([nasiak, mean_std], axis=1)
df

                  1            2            3         mean        std
AIR     4608.000000  4450.000000  4546.153846  4534.717949  79.618370
FREEZE  3477.777778  3510.526316  3557.894737  3515.399610  40.280188

In [93]:
print(df.to_latex(float_format="%.1f"))
df

\begin{tabular}{lrrrrr}
\toprule
 & 1 & 2 & 3 & mean & std \\
\midrule
AIR & 4608.0 & 4450.0 & 4546.2 & 4534.7 & 79.6 \\
FREEZE & 3477.8 & 3510.5 & 3557.9 & 3515.4 & 40.3 \\
\bottomrule
\end{tabular}

                  1            2            3         mean        std
AIR     4608.000000  4450.000000  4546.153846  4534.717949  79.618370
FREEZE  3477.777778  3510.526316  3557.894737  3515.399610  40.280188

In [94]:
ph = pd.DataFrame(
    [
        [6.600, 6.581, 6.680],
        [6.700, 6.742, 6.667],
    ],
    columns=["1", "2", "3"],
    index=["AIR", "FREEZE"],
)
ph

          1      2      3
AIR     6.6  6.581  6.680
FREEZE  6.7  6.742  6.667

In [95]:
ref_ph = 6.190
ref_ph

6.19

In [96]:
mean_std = pd.concat([ph.mean(axis=1), ph.std(axis=1)], axis=1)
mean_std.columns = ["mean", "std"]
mean_std = mean_std.round(3)
mean_std

         mean    std
AIR     6.620  0.053
FREEZE  6.703  0.038

In [97]:
diff = ph - ref_ph

diff_mean_std = pd.concat([diff.mean(axis=1), diff.std(axis=1)], axis=1)
diff_mean_std.columns=["śr. zmiana", "STD"]
diff_mean_std = diff_mean_std.round(3)
diff_mean_std

        śr. zmiana    STD
AIR          0.430  0.053
FREEZE       0.513  0.038

In [105]:
ph.to_numpy()[0]

array([6.6  , 6.581, 6.68 ])

In [109]:
t_stat, p_value = stats.ttest_rel(ph.to_numpy(), np.ones((2, 3)) * ref_ph, axis=1)
p_value

array([0.00493183, 0.00178493])

In [99]:
ph_mean_std = pd.concat([ph, mean_std, diff_mean_std], axis=1)
ph_mean_std

          1      2      3   mean    std  śr. zmiana    STD
AIR     6.6  6.581  6.680  6.620  0.053       0.430  0.053
FREEZE  6.7  6.742  6.667  6.703  0.038       0.513  0.038

In [100]:
print(ph_mean_std.to_latex(float_format="%.3f"))

\begin{tabular}{lrrrrrrr}
\toprule
 & 1 & 2 & 3 & mean & std & śr. zmiana & STD \\
\midrule
AIR & 6.600 & 6.581 & 6.680 & 6.620 & 0.053 & 0.430 & 0.053 \\
FREEZE & 6.700 & 6.742 & 6.667 & 6.703 & 0.038 & 0.513 & 0.038 \\
\bottomrule
\end{tabular}