In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
pre = pd.DataFrame(
    [
        [0.080, 0.076, 0.086],  # CEL
        [0.115, 0.113, 0.124],  # JOD
        [0.050, 0.053, 0.051],  # GAZ
    ],
    index=["CEL", "JOD", "GAZ"],
    columns=["1", "2", "3"],
)
pre

         1      2      3
CEL  0.080  0.076  0.086
JOD  0.115  0.113  0.124
GAZ  0.050  0.053  0.051

In [18]:
post = pd.DataFrame(
    [
        [0.644, 0.667, 0.784],  # CEL
        [0.093, 0.109, 0.105],  # JOD
        [0.433, 0.408, 0.418],  # GAZ
    ],
    index=["CEL", "JOD", "GAZ"],
    columns=["1", "2", "3"],
)
post

         1      2      3
CEL  0.644  0.667  0.784
JOD  0.093  0.109  0.105
GAZ  0.433  0.408  0.418

In [19]:
nasiak = 100*(post - pre)/pre  # %
nasiak

              1           2           3
CEL  705.000000  777.631579  811.627907
JOD  -19.130435   -3.539823  -15.322581
GAZ  766.000000  669.811321  719.607843

In [22]:
mean_std = pd.concat([nasiak.mean(axis=1), nasiak.std(axis=1)], axis=1)
mean_std.columns = ["mean", "std"]
mean_std

           mean        std
CEL  764.753162  54.468044
JOD  -12.664279   8.128144
GAZ  718.473055  48.104379

In [24]:
df = pd.concat([nasiak, mean_std], axis=1)
df

              1           2           3        mean        std
CEL  705.000000  777.631579  811.627907  764.753162  54.468044
JOD  -19.130435   -3.539823  -15.322581  -12.664279   8.128144
GAZ  766.000000  669.811321  719.607843  718.473055  48.104379

In [25]:
df.to_latex()

'\\begin{tabular}{lrrrrr}\n\\toprule\n & 1 & 2 & 3 & mean & std \\\\\n\\midrule\nCEL & 705.000000 & 777.631579 & 811.627907 & 764.753162 & 54.468044 \\\\\nJOD & -19.130435 & -3.539823 & -15.322581 & -12.664279 & 8.128144 \\\\\nGAZ & 766.000000 & 669.811321 & 719.607843 & 718.473055 & 48.104379 \\\\\n\\bottomrule\n\\end{tabular}\n'